kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-provider-pvc
  namespace: drone
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi