apiVersion: v1
kind: Service
metadata:
  name: drone-provider-service
  namespace: drone
spec:
  selector:
    app: drone-provider
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 9001