apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-provider-deployment
  namespace: drone
  labels:
    app: drone-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-provider
  template:
    metadata:
      labels:
        app: drone-provider
    spec:
      containers:
        - name: drone-provider
          image: drone/drone:1
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: DRONE_RUNNER_CAPACITY
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.runner.capacity
            - name: DRONE_GITHUB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.github.server
            - name: DRONE_GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.github.client.id
            - name: DRONE_GITHUB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.github.client.secret
            - name: DRONE_GIT_ALWAYS_AUTH
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.git.always.auth
            - name: DRONE_RPC_SECRET
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.rpc.secret
            - name: DRONE_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.server.host
            - name: DRONE_SERVER_PROTO
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.server.proto
            - name: DRONE_LOGS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.server.debug
            - name: DRONE_LOGS_PRETTY
              valueFrom:
                configMapKeyRef:
                  name: drone-provider-config
                  key: drone.server.debug
          volumeMounts:
            - name: drone-provider-pvc
              mountPath: "/data"
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: drone-provider-pvc
          persistentVolumeClaim:
            claimName: drone-provider-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock