version: '3'
services:
  drone:
    image: drone/drone:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/drone:/data
    environment:
      DRONE_GITHUB_SERVER: https://github.com
      DRONE_GITHUB_CLIENT_ID:
      DRONE_GITHUB_CLIENT_SECRET:
      DRONE_RUNNER_CAPACITY:
      DRONE_SERVER_HOST:
      DRONE_SERVER_PROTO: https
      DRONE_TLS_AUTOCERT: false

    ports:
      - "80:80"
      - "443:443"


